### PR TITLE
Minor version upgrade + bitcode (different from the one on NPM)

### PR DESCRIPTION
**Pull request by ramicaza**
This PR includes all the changes needed to bump the minor version ViroReact.

-Fixes the issues in [Viro issue 56](https://github.com/ViroCommunity/viro/issues/56) using @doranteseduardo's [comment](https://github.com/ViroCommunity/viro/issues/56#issuecomment-986437376)

-Bumps the RN version to 0.65

-Additionally, it recompiles all the ios/Libraries with bitcode enabled for arm64 & armv7

-Finally, I set the chroma_threshold_sensitivity default to a more sensible 0.1 that filters out a smaller color space surrounding the target chroma key filter.

### CODE REVIEW

**Comment by hannesa2** [comment]
I recommend to rebase to recent master to have a proper CI build

**Comment by hannesa2** [comment]
@doranteseduardo Sadly, now you merged a broken pull request which results into a broken master https://github.com/ViroCommunity/virocore/actions/runs/1678419635

**Comment by doranteseduardo** [comment]
OMG it ran well locally, I'll revert.

**Comment by ramicaza** [comment]
Thanks @hannesa2 and sorry for the confusion @doranteseduardo. Will submit a new PR today rebased with main and i'll try to incorporate the changes in branch 2.22.1 on the /viro repo

**Pull request merged**
